# Generated by Django 5.2.8 on 2025-11-13 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('factor', models.FloatField(default=1.0, help_text='Multiplier for pricing based on bus type')),
                ('is_model_trained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, help_text="Duration string for journey (e.g. '4:43hrs')", max_length=50, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_stop', models.CharField(blank=True, help_text='Additional pickup stop location', max_length=255, null=True)),
                ('return_pickup_stop', models.CharField(blank=True, help_text='Return pickup stop location for roundtrip', max_length=255, null=True)),
                ('final_destination', models.CharField(blank=True, help_text='Final destination for roundtrip journeys', max_length=255, null=True)),
                ('final_pickup', models.CharField(blank=True, help_text='Final pickup for roundtrip journeys', max_length=255, null=True)),
                ('is_roundtrip', models.BooleanField(default=False)),
                ('stops_count', models.IntegerField(default=0)),
                ('roundtrip_stops_count', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_passengers', models.IntegerField()),
                ('travel_date', models.DateField()),
                ('pickup_time', models.TimeField(default=django.utils.timezone.now)),
                ('roundtrip_pickup_date', models.DateField(blank=True, null=True)),
                ('roundtrip_pickup_time', models.TimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(choices=[('UNCOVERED AREA', 'We dont service that area.'), ('NO BUSSES', 'No busses available for that date.'), ('INCOMPLETE INFO', 'We need more information to provide a quote.')], default='', max_length=255)),
                ('special_instructions', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('pickup_reminder_sent', models.DateTimeField(blank=True, help_text='Timestamp of last pickup reminder email sent', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('payment_type', models.CharField(blank=True, choices=[('completed', 'Completed'), ('split', 'Split')], max_length=20, null=True)),
                ('split_counts', models.PositiveIntegerField(blank=True, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_students', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_teachers', models.PositiveIntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calculated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('temp_password', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='quotations.lead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(help_text='Reason or comment for rejecting the price or lead.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='quotations.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('pickup_time', models.TimeField(default=django.utils.timezone.now)),
                ('roundtrip_pickup_date', models.DateField(blank=True, null=True)),
                ('roundtrip_pickup_time', models.TimeField(blank=True, null=True)),
                ('is_roundtrip', models.BooleanField(default=False)),
                ('stops_count', models.IntegerField(default=0)),
                ('roundtrip_stops_count', models.IntegerField(default=0)),
                ('rejection_reason', models.CharField(choices=[('UNCOVERED AREA', 'We dont service that area.'), ('NO BUSSES', 'No busses available for that date.'), ('INCOMPLETE INFO', 'We need more information to provide a quote.')], default='', max_length=255)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_passengers', models.IntegerField()),
                ('special_instructions', models.TextField(blank=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('needs_review', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('QUOTE_CREATED', 'Quote Created'), ('STATUS_UPDATE', 'Status Update'), ('PRICE_UPDATE', 'Price Update'), ('ADMIN_UPDATE', 'Admin Update'), ('PAYMENT_UPDATE', 'Payment Update'), ('TRIP_APPROVED', 'Lead Approved'), ('TRIP_REJECTED', 'Lead Rejected'), ('CHAT_USER', 'Chat Message (User)'), ('CHAT_ADMIN', 'Chat Message (Admin)')], default='ADMIN_UPDATE', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.lead')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_record', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='RoundtripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('estimated_time', models.IntegerField(default=30)),
                ('order', models.IntegerField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roundtrip_stops', to='quotations.quotation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoundtripStopLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('estimated_time', models.IntegerField(default=30)),
                ('order', models.IntegerField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roundtrip_stops_lead', to='quotations.lead')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('estimated_time', models.IntegerField(default=30)),
                ('order', models.IntegerField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='quotations.quotation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StopLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('estimated_time', models.IntegerField(default=30)),
                ('order', models.IntegerField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops_lead', to='quotations.lead')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('COMPLETE', 'Complete Payment'), ('SPLIT', 'Split Payment')], max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('total_splits_count', models.IntegerField(blank=True, null=True)),
                ('amount_per_split', models.DecimalField(decimal_places=2, max_digits=10)),
                ('split_paid_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='quotations.lead')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='quotations.lead')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('SIGNUP', 'Signup Verification'), ('LOGIN', 'Login Verification'), ('RESET', 'Password Reset')], max_length=20)),
                ('_registration_data', models.TextField(blank=True, db_column='registration_data', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose'], name='quotations__email_7650b4_idx')],
            },
        ),
    ]
