# Generated by Django 5.2.8 on 2026-01-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_xerotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('PAY_LATER', 'Pay Later'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
