# Generated by Django 5.2.8 on 2026-01-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='outbound_arrival_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='return_arrival_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
