# Generated by Django 6.0.1 on 2026-01-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_lead_outbound_arrival_time_lead_return_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reminder_processed',
            field=models.BooleanField(default=False, help_text='Indicates if the reminder was processed (even if skipped)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
