# Generated by Django 6.0.1 on 2026-01-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_lead_reminder_processed_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
    ]
