# Generated by Django 6.0.1 on 2026-02-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_lead_invoice_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlead',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
