# Generated by Django 6.0.1 on 2026-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_transaction_admin_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlead',
            name='admin_message',
        ),
        migrations.AddField(
            model_name='lead',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
