# Generated by Django 6.0.1 on 2026-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_remove_transactionlead_admin_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('PAY_LATER', 'Pay Later'), ('CANCELLED', 'Cancelled'), ('EDITED', 'Edited')], default='PENDING', max_length=10),
        ),
    ]
