# Generated by Django 6.0.1 on 2026-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
