# Generated by Django 6.0.1 on 2026-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_lead_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='is_edited',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
