# Generated by Django 6.0.1 on 2026-02-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_alter_lead_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('RETURN', 'Return')], help_text='OUTBOUND or RETURN', max_length=10)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('arrival_time', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationprice',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='roundtripstoplead',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='stoplead',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='transactionlead',
            name='lead',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='quotation',
            new_name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='final_destination',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='final_pickup',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='outbound_arrival_time',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='pickup_stop',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='return_arrival_time',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='return_pickup_stop',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='roundtrip_pickup_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='roundtrip_pickup_time',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='roundtrip_stops_count',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='stops_count',
        ),
        migrations.AlterField(
            model_name='lead',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='number_of_passengers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='outbound_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_outbound', to='quotations.trip'),
        ),
        migrations.AddField(
            model_name='lead',
            name='return_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_return', to='quotations.trip'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('estimated_time', models.IntegerField(default=30)),
                ('stop_order', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='quotations.trip')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
        migrations.DeleteModel(
            name='RoundtripStop',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.DeleteModel(
            name='QuotationPrice',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='RoundtripStopLead',
        ),
        migrations.DeleteModel(
            name='StopLead',
        ),
        migrations.DeleteModel(
            name='TransactionLead',
        ),
    ]
