# Generated by Django 6.0.1 on 2026-02-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_trip_remove_quotation_user_remove_stop_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('BOOKED', 'Booked'), ('PAY_LATER', 'Pay Later'), ('CANCELLED', 'Cancelled'), ('EDITED', 'Edited')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('SPLIT', 'Split Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
